### ISSUE TITLE
springboot环境下NacosRefresher初始化时DtpProperties的属性未注入

### ISSUE THREAD

**Issue by 1625567290** [dromara/dynamic-tp#111]
### 使用方面
使用的官方提供的example
springboot环境下NacosRefresher初始化时DtpProperties的属性没有nacos配置文件的注入

![image](https://user-images.githubusercontent.com/79852400/215112996-2a0fe596-e956-4179-9c70-d21e20ad0b7f.png)
![image](https://user-images.githubusercontent.com/79852400/215113087-2c2289bb-31f3-4d42-9f21-4655b2a0cd65.png)

求解答

**Comment by yanhom1314** [comment]
data-ids没配置？截图看看application.yml

**Comment by yanhom1314** [comment]
nacos配置文件名称是啥

**Comment by yanhom1314** [comment]
nacos配置文件名称是啥

**Comment by 1625567290** [comment]
> nacos配置文件名称是啥

dynamic-tp-nacos-cloud-demo-dtp-dev.yml

**Comment by yanhom1314** [comment]
多了个cloud（手动汗）

**Comment by 1625567290** [comment]
> 多了个cloud（手动汗）

我眼瞎了
