### ISSUE TITLE
springboot版本不兼容导致类(CompositeHealthContributor)无法found

### ISSUE THREAD

**Issue by ancientelves** [dromara/dynamic-tp#113]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：8
- SpringBoot版本：2.1.18.RELEASE
- DynamicTp版本：
<dependency>
        <groupId>cn.dynamictp</groupId>
        <artifactId>dynamic-tp-spring-boot-starter-common</artifactId>
        <version>1.0.9</version>
    </dependency>

- 配置中心版本：

### 问题描述

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.health.CompositeHealthContributor

- 猜测可能原因：
CompositeHealthContributor 无法在低版本springboot的监控组件中
spring-boot-starter-actuator

**Comment by yanhom1314** [comment]
这就是版本不兼容导致的呗，CompositeHealthContributor 是哪个依赖里会用到的，升级版本吧
