### ISSUE TITLE
dynamic-tp-example-adapter拆分

### ISSUE THREAD

**Issue by dragon-zhang** [dromara/dynamic-tp#115]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
目前所有adapter的例子都在dynamic-tp-example-adapter模块，建议拆分为多个模块

### 难度风险
无风险

**Comment by yanhom1314** [comment]
留给社区小伙伴做了
