### ISSUE TITLE
question: 注册成功的 bean 但是找不到

### ISSUE THREAD

**Issue by amosnothing** [dromara/dynamic-tp#135]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 使用方面

> 2023-02-14 12:35:40.976 [main] [INFO] [c.d.c.DtpRegistry] [] - DtpRegistry initialization is complete, remote dtpExecutors: [cronTaskServiceExecutor, `userTaskServiceExecutor`], local dtpExecutors: [], local commonExecutors: []
> ... 
> 2023-02-14 13:11:07.350 [http-nio-725-exec-9] [ERROR] [c.d.c.DtpRegistry] [15b57af9a9362a25effffd64a527f9c7] - Cannot find a specified dtpExecutor, name: `userTaskServiceExecutor`

**Comment by amosnothing** [comment]
线程池配置全部是通过 nacos 配置的

**Comment by yanhom1314** [comment]
不应该吧，截图详细点

**Comment by amosnothing** [comment]
没有截图哦，我修改成 Resource 注解就可以。
