### ISSUE TITLE
支持spring老项目吗

### ISSUE THREAD

**Issue by skyemin** [dromara/dynamic-tp#136]
如题

**Comment by yanhom1314** [comment]
目前只支持springboot 2.X项目

**Comment by dragon-zhang** [comment]
指派给我吧，正好最近由于公司需要，在做SpringMVC的支持。@yanhom1314

**Comment by liulei0903** [comment]
@dragon-zhang 老哥，我和你相同的需求，也是 spring 老项目想使用，你改造成功了吗？

**Comment by dragon-zhang** [comment]
> @dragon-zhang 老哥，我和你相同的需求，也是 spring 老项目想使用，你改造成功了吗？

内部改造ok，同步到社区，估计得2周噢

**Comment by wuhanxue** [comment]
> > @dragon-zhang 老哥，我和你相同的需求，也是 spring 老项目想使用，你改造成功了吗？
> 
> 内部改造ok，同步到社区，估计得2周噢

@dragon-zhang  请问同步的怎么样了

**Comment by dragon-zhang** [comment]
> > > @dragon-zhang 老哥，我和你相同的需求，也是 spring 老项目想使用，你改造成功了吗？
> > 
> > 
> > 内部改造ok，同步到社区，估计得2周噢
> 
> @dragon-zhang 请问同步的怎么样了

完成了30%吧

**Comment by dragon-zhang** [comment]
目前大概60%

**Comment by dragon-zhang** [comment]
@skyemin @liulei0903 @ wuhanxue 完成了，在https://github.com/dromara/dynamic-tp/tree/springmvc_support 各位可以先用用看

**Comment by liulei0903** [comment]
> 

好的老哥，下周一试试

**Comment by jzzyyy** [comment]
springmvc dubbo可以使用吗

**Comment by dragon-zhang** [comment]
支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jzzyyy ***@***.***&gt;
发送时间: 2023年12月1日 16:55
收件人: dromara/dynamic-tp ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [dromara/dynamic-tp] 支持spring老项目吗 (Issue #136)





 
springmvc dubbo可以使用吗

**Comment by chenzhihao1040728129** [comment]
> @skyemin @liulei0903 @wuhanxue 完成了，在https://github.com/dromara/dynamic-tp/tree/springmvc_support 各位可以先用用看

您好, 首先感谢作者的辛苦实现,
spring 老项目引用的依赖是?  是将该分支上那些项目打包引入?  配置示例是?
我看example上没有示例
