### ISSUE TITLE
有没有办法关掉默认开启的线程池告警

### ISSUE THREAD

**Issue by TOPG1994** [dromara/dynamic-tp#157]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 使用方面
我们主要的场景是针对dubbo线程池、undertow线程池和业务线程池进行监控和告警。不会用到动态变更线程池参数的功能。

但是我们只想针对dubbo线程池和undertow线程池做告警，业务线程池我们只打算通过指标收集的方式进行观测。这样就会有一个问题，如果我们配置了spring.dynamic.tp.platforms[0].platform 的话，必须针对多个业务线程池也进行告警的配置，不然默认也是会进行告警的。原因是这个代码(所有的非DtpExecutor 线程池都会走到这个构造器)：
![image](https://user-images.githubusercontent.com/19574020/221820913-c7aa0487-fc88-4b7b-951e-6c677c82b327.png)

所以想问两个问题：
1. 有没有办法统一关闭线程池的告警，只有配置了告警规则的线程池才进行告警
2. 考虑到不同的线程池可能需要推送到不同的告警群(例如dubbo线程池告警推送到统一的基础服务群，然后业务线程池推送到线程池所属微服务的群)，后续能否新增 feature 来支持。个人觉得还是比较有必要的。

**Comment by yanhom1314** [comment]
notifyEnabled 可以通过这个字段配置

**Comment by TOPG1994** [comment]
notifyEnabled 这个配置看到了，但是我的表达可能没有太清楚。我们希望是使用@DynamicTp 声明线程池的时候只是接入监控功能，告警的话不想再去配置文件里面配置notifyEnabled 来把告警关闭。因为我们有蛮多微服务都要接，如果每个业务线程池都加这个配置，未免也太麻烦了。

**Comment by yanhom1314** [comment]
告警默认是开启的，如需关闭告警
1.可以全局不配platforms
2.可以线程池配置加notifyEnabled =false
3.如果只是关闭某一报警项，可以用NotifyItem.enabled字段

**Comment by yanhom1314** [comment]
你说第二点我觉得是可以的，候选会考虑支持

**Comment by KamToHung** [comment]
> 你说第二点我觉得是可以的，候选会考虑支持

这边打算支持吗，可以的话我可以完成此需求

**Comment by yanhom1314** [comment]
> > 你说第二点我觉得是可以的，候选会考虑支持
> 
> 这边打算支持吗，可以的话我可以完成此需求

👍🏻，可以搞下
