### ISSUE TITLE
使用properties格式在nacos配置，按照教程配置了钉钉推送，发现nacos修改线程池参数的时候并未推送通知

### ISSUE THREAD

**Issue by shihaowei-david** [dromara/dynamic-tp#161]
配置文件：
dynamic-tp.properties
配置内容：
![image](https://user-images.githubusercontent.com/59689361/222445325-96ac9326-cff2-4616-a6a9-d44e88902b9f.png)

线程是注册上了的，都能在日志nacos看到线程配置信息，但是在nacos修改线程池参数并未收到钉钉推送通知
com.dtp.core.DtpRegistry - DynamicTp register dtpExecutor, source: beanPostProcessor, executor: DtpMainProp(threadPoolName=dtpExecutorMemServer, corePoolSize=32, maxPoolSize=256, keepAliveTime=60, queueType=VariableLinkedBlockingQueue, queueCapacity=2000, rejectType=CallerRunsPolicy, allowCoreThreadTimeOut=false)

**Comment by yanhom1314** [comment]
非SpringCloud场景下nacos需配置spring.dynamic.tp.nacos.dataId=dynamic-tp-demo-dev.yml
