### ISSUE TITLE
ScheduledThreadPoolExecutor JDK8 BUG

### ISSUE THREAD

**Issue by KamToHung** [dromara/dynamic-tp#164]
### 方案描述

JDK8中，ScheduledThreadPoolExecutor若配置corePoolSize=0会存在CPU 100% BUG

[JDK-8065320](https://bugs.openjdk.org/browse/JDK-8065320)

为了使得程序更具有健壮性，我想加个版本判断的工具类，并且在ScheduledDtpExecutor做一些优化，例如当JDK9版本做一些避免此BUG出现的操作

### 应用场景

ScheduledDtpExecutor更具有健壮性，并且新增的JDK版本工具类可以为以后需要根据版本进行优化的地方提供相关功能

### 难度风险
无

### 外部依赖
无

若允许的话，我这边可以提交pr

**Comment by yanhom1314** [comment]
可以啊
