### ISSUE TITLE
question: 能否提供 dynamic-tp 最佳实践的 grafana dashboards 💗

### ISSUE THREAD

**Issue by CherishCai** [dromara/dynamic-tp#175]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 使用方面
能否提供 dynamic-tp 最佳实践的 grafana dashboards 💗

https://dynamictp.cn/guide/monitor/prometheus_grafana.html

**Comment by yanhom1314** [comment]
项目example下有一个json文件

**Comment by CherishCai** [comment]
感谢🙏，楼主大爱
