### ISSUE TITLE
启动优化

### ISSUE THREAD

**Issue by KamToHung** [dromara/dynamic-tp#176]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
通过@EnableDynamicTp注解决定与dtp中spring相关自动装配，不再使用spring.dynamic.tp.enabled
### 应用场景
启动时候只通过@EnableDynamicTp决定是否使用dtp
### 难度风险
无
### 外部依赖
无

如果可以，我这边可提pr

**Comment by yanhom1314** [comment]
可以的老哥
