### ISSUE TITLE
使用flatten-maven-plugin进行版本统一管理

### ISSUE THREAD

**Issue by KamToHung** [dromara/dynamic-tp#182]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
使用flatten-maven-plugin进行版本统一管理
### 应用场景
现阶段每个模块都要自己指定一次版本，我这边想通过在dynamic-tp-all通过指定了版本即可，其他模块通过${revision}进行版本指定。打包的时候需要用到flatten-maven-plugin插件
### 难度风险
无
### 外部依赖
打包时需要flatten-maven-plugin插件

**Comment by yanhom1314** [comment]
思路没问题，我之前用过这个，但是有些问题，比如我只发布一个子模块，会导致其他模块版本号取${project.version}，导致引入pom后无法下载，需发布私仓测试下是否有问题

**Comment by KamToHung** [comment]
> 思路没问题，我之前用过这个，但是有些问题，比如我只发布一个子模块，会导致其他模块版本号取${project.version}，导致引入pom后无法下载，需发布私仓测试下是否有问题

我这边测试了下:
1. 升级版本直接deploy单个模块，和master一样失败
2. 升级版本本地install，deploy单个模块到私仓，然后删除本地，和master一样拉取失败
3. 升级版本整个deploy，和master一样成功可以拉取

验证结果:
整体校验和master分支一样，master发布后能下载下来的话这种方式也可以
jar包里面的pom.xml也是一样
![image](https://user-images.githubusercontent.com/16450524/228135540-32a8a9e4-3e8d-4a6e-a77b-f18d05842a01.png)

**Comment by yanhom1314** [comment]
> 

好，我改天打个snapshot包先试试
