### ISSUE TITLE
当服务停止AlarmManager中的dtp-alarm线程池没有运行destroy

### ISSUE THREAD

**Issue by KamToHung** [dromara/dynamic-tp#196]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
因为AlarmManager中的dtp-alarm线程池是DtpExecutor没有给spring托管，所以服务停止后也不会调用destroy进行关闭。
建议可以放在DtpBaseBeanConfiguration中定义，或者通过Runtime.getRuntime().addShutdownHook() shutdown
### 难度风险
无
### 外部依赖
无

**Comment by yanhom1314** [comment]
两种方式都可以
