### ISSUE TITLE
线程池内部注册器优化

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#212]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述

统一管理 DtpRegistry 中的 DTP_REGISTRY 和 COMMON_REGISTRY，不在分开维护
<img width="845" alt="image" src="https://user-images.githubusercontent.com/13051908/230710247-cd336578-1612-4aac-87a1-aca2fd30e71a.png">

### 难度风险
低
### 外部依赖
无

**Comment by KamToHung** [comment]
please assgined  me
