### ISSUE TITLE
优雅关闭线程池

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#236]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
当Spring容器在关闭的时候，线程池里可能还有任务在执行，任务中会使用到Spring中某些bean，但此时这些bean有可能已经被销毁，就会有异常出现，影响业务，需要在这些依赖bean销毁前关闭线程池。

可以在 1或2步骤中进行线程池关闭
![image](https://user-images.githubusercontent.com/13051908/232313132-11e5bb4e-5d1c-433f-b322-70542688c46d.png)

### 应用场景
优雅关闭线程池
### 难度风险
中
### 外部依赖
无

**Comment by KamToHung** [comment]
使用ApplicationContextHolder.getBean的时候找不到Bean，如果是本身注解/构造器/set注入的话引用还在，这个确实需要解决

**Comment by KamToHung** [comment]
如果是本身注解/构造器/set注入的话引用还在，但是使用ApplicationContextHolder.getBean会找不到Bean，这个确实需要解决

**Comment by yanhom1314** [comment]
https://gitee.com/dromara/dynamic-tp/issues/I6VZH3#note_17539084

**Comment by yanhom1314** [comment]
> https://gitee.com/dromara/dynamic-tp/issues/I6VZH3#note_17539084



> 如果是本身注解/构造器/set注入的话引用还在，但是使用ApplicationContextHolder.getBean会找不到Bean，这个确实需要解决

对的

**Comment by yanhom1314** [comment]
> 如果是本身注解/构造器/set注入的话引用还在，但是使用ApplicationContextHolder.getBean会找不到Bean，这个确实需要解决

是的
