### ISSUE TITLE
使用log4j2的日志应用，引入dynamic-tp starter之后项目起不来

### ISSUE THREAD

**Issue by zhoule-le** [dromara/dynamic-tp#24]
项目上使用的是log4j2的日志，排除了logback相关的依赖，但是dynamic-tp-logging模块又引入了logback的相关依赖，导致和log4j2的冲突，而且DtpLogging里面硬编码引入了logback的包，这边建议可以支持logback和log4j2两种依赖，还有就是DtpLoggingListener类里面有个判断逻辑是判断项目是不是有cloud环境，我们就是用的apllo没有cloud环境，这块是否也可以优化，比如sources.contains()里面的值直接用上面反射得到的结果代替
![PA1UNQ86WD3R _G6Y9AOU`P](https://user-images.githubusercontent.com/53507244/162386997-7199066e-236d-426f-bc59-05254f11be7d.png)

**Comment by lyh200** [comment]
log4j2依赖最近会加上，预计1.0.5版本发布

**Comment by lyh200** [comment]
> 项目上使用的是log4j2的日志，排除了logback相关的依赖，但是dynamic-tp-logging模块又引入了logback的相关依赖，导致和log4j2的冲突，而且DtpLogging里面硬编码引入了logback的包，这边建议可以支持logback和log4j2两种依赖，还有就是DtpLoggingListener类里面有个判断逻辑是判断项目是不是有cloud环境，我们就是用的apllo没有cloud环境，这块是否也可以优化，比如sources.contains()里面的值直接用上面反射得到的结果代替 ![PA1UNQ86WD3R _G6Y9AOU`P](https://user-images.githubusercontent.com/53507244/162386997-7199066e-236d-426f-bc59-05254f11be7d.png)

最新代码已加入log4j2支持，可以拉master代码自己打包测试下，1.0.5版本发布会带上
