### ISSUE TITLE
dynamic-tp与skywalking冲突

### ISSUE THREAD

**Issue by psc0606** [dromara/dynamic-tp#250]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：jdk17
- SpringBoot版本：2.7.7
- DynamicTp版本：1.1.2
- 配置中心版本：1.4

### 问题描述
ClassCastException: class org.apache.skywalking.apm.plugin.wrapper.SwRunnableWrapper cannot be cast to class com.dtp.core.support.runnable.DtpRunnable (org.apache.skywalking.apm.plugin.wrapper.SwRunnableWrapper is in unnamed module of loader org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader @64a294a6; com.dtp.core.support.runnable.DtpRunnable is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1cb7936c)

应该是skywalking对线程池的增强与dynamicTp冲突

### 复现步骤
引入对应的包即可

**Comment by KamToHung** [comment]
可以提供下skywalking插件版本吗

**Comment by psc0606** [comment]
`
            
            <dependency>
                <groupId>cn.dynamictp</groupId>
                <artifactId>dynamic-tp-spring-boot-starter-apollo</artifactId>
                <version>1.1.2</version>
            </dependency>
            <dependency>
                <groupId>cn.dynamictp</groupId>
                <artifactId>dynamic-tp-spring-boot-starter-adapter-webserver</artifactId>
                <version>1.1.2</version>
            </dependency>
            <dependency>
                <groupId>cn.dynamictp</groupId>
                <artifactId>dynamic-tp-spring-boot-starter-adapter-dubbo</artifactId>
                <version>1.1.2</version>
            </dependency>
            <dependency>
                <groupId>cn.dynamictp</groupId>
                <artifactId>dynamic-tp-extension-skywalking</artifactId>
                <version>1.1.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-trace</artifactId>
                <version>8.11.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-logback-1.x</artifactId>
                <version>8.11.0</version>
            </dependency>
`
看错误是 skywalking agent 包（8.11.0版本的包）对线程的增强与dynamic-tp发生冲突；

**Comment by yanhom1314** [comment]
> ```
>             
>             <dependency>
>                 <groupId>cn.dynamictp</groupId>
>                 <artifactId>dynamic-tp-spring-boot-starter-apollo</artifactId>
>                 <version>1.1.2</version>
>             </dependency>
>             <dependency>
>                 <groupId>cn.dynamictp</groupId>
>                 <artifactId>dynamic-tp-spring-boot-starter-adapter-webserver</artifactId>
>                 <version>1.1.2</version>
>             </dependency>
>             <dependency>
>                 <groupId>cn.dynamictp</groupId>
>                 <artifactId>dynamic-tp-spring-boot-starter-adapter-dubbo</artifactId>
>                 <version>1.1.2</version>
>             </dependency>
>             <dependency>
>                 <groupId>cn.dynamictp</groupId>
>                 <artifactId>dynamic-tp-extension-skywalking</artifactId>
>                 <version>1.1.2</version>
>             </dependency>
>             <dependency>
>                 <groupId>org.apache.skywalking</groupId>
>                 <artifactId>apm-toolkit-trace</artifactId>
>                 <version>8.11.0</version>
>             </dependency>
>             <dependency>
>                 <groupId>org.apache.skywalking</groupId>
>                 <artifactId>apm-toolkit-logback-1.x</artifactId>
>                 <version>8.11.0</version>
>             </dependency>
> ```
> 
> 看错误是 skywalking agent 包（8.11.0版本的包）对线程的增强与dynamic-tp发生冲突；

agent咋配置的，这几个依赖包我也用了，没问题的

**Comment by psc0606** [comment]
只引用以上依赖包skywalking不会生效，需要配置skywaling的agent如下：
-javaagent:/data/pinpoint/skywalking-agent/skywalking-agent.jar=plugin.exclude_plugins='kafka-0.11.x/1.x/2.x'
-Dskywalking.logging.dir=/data/logs/skywalking
-Dskywalking.agent.service_name=${NAMESPACE}::${SERVICE_NAME}
-Dskywalking.collector.backend_service=${SKYWALKING_OAP_ADDRESS}
-Dskywalking.agent.is_cache_enhanced_class=false

**Comment by hj-545** [comment]
![image](https://github.com/dromara/dynamic-tp/assets/15043395/e051e687-6272-46b8-befe-c09bf5e2e40c)
说的是这2个插件？

**Comment by yanhom1314** [comment]
简单修复了下，目前不会报错，但是任务维度监控功能会损失
