### ISSUE TITLE
tomcat-embed-core 9.0.50及以下版本getRejectedExecutionHandler报NoSuchMethodError错误

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#261]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：jdk8
- SpringBoot版本：2.3.12.RELEASE
- DynamicTp版本：1.1.3

### 问题描述

[gitee issue](https://gitee.com/dromara/dynamic-tp/issues/I71LKM)

**Comment by applenele** [comment]
这个问题还没release吧，我也遇到这个问题。

**Comment by beareverse** [comment]
目前只能手动指定跟dtp一样的版本：
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>9.0.63</version>
            </dependency>
