### ISSUE TITLE
接入dynamic-tp-spring-boot-starter-adapter-dubbo 启动异常

### ISSUE THREAD

**Issue by xinruilf** [dromara/dynamic-tp#269]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：
- SpringBoot版本：
- DynamicTp版本：1.1.3
- 配置中心版本：apollo

### 问题描述
使用  接入 dynamic-tp-spring-boot-starter-adapter-dubbo 
启动异常
![image](https://github.com/dromara/dynamic-tp/assets/134294855/9ba6dcf2-1736-44ae-a3ef-34b9d1a7c736)

**Comment by yanhom1314** [comment]
dubbo 那个版本

**Comment by xinruilf** [comment]
> dubbo 那个版本

dubbo 是3.2.0版本
