### ISSUE TITLE
线程池打满时报java.lang.ClassCastException:

### ISSUE THREAD

**Issue by zhaoguozhenjava** [dromara/dynamic-tp#282]
<img width="803" alt="image" src="https://github.com/dromara/dynamic-tp/assets/13815308/e0c6585e-ae4f-4ea3-8d10-8fe656ea3fcc">

**Comment by yanhom1314** [comment]
使用了agent模式的ttl？

**Comment by zhaoguozhenjava** [comment]
> 
使用的阿里云的agent链路追踪，线程创建是用的一般的创建方法
