### ISSUE TITLE
拉取dubboTp为空

### ISSUE THREAD

**Issue by applenele** [dromara/dynamic-tp#284]
版本信息

Jdk版本：1.8
SpringBoot版本：2.3.12.RELEASE
DynamicTp版本：1.1.13
配置中心版本： apollo

问题描述
dubbo 2.6.5 ,接入dynamic-tp-spring-boot-starter-adapter-dubbo  ,apollo 配置了dubboTp, refresh properties 能拉到配置,  但是bind之后 dubboTp 是null。

![image](https://github.com/dromara/dynamic-tp/assets/5456023/1f18aad4-45b1-478c-94cf-ba357974fa4a)

<img width="1257" alt="image" src="https://github.com/dromara/dynamic-tp/assets/5456023/f8a8e0ae-6bb3-4154-86fc-a38886c0e440">

<img width="1059" alt="image" src="https://github.com/dromara/dynamic-tp/assets/5456023/5e920aad-a53a-4d3e-9008-0dabd8e3d301">

**Comment by yanhom1314** [comment]
这么奇怪？apollo版本是多少

**Comment by applenele** [comment]
apollo 1.2 
apollo-client 1.5

**Comment by KamToHung** [comment]
> 问题解决了。 dubboTp 需要以数组的形式配置。
> 
> ![image](https://user-images.githubusercontent.com/5456023/244984537-12baacfd-6635-4f90-b77e-d11a0a01efb2.png)
> 
> 但是啥场景会开多个dubbo端口呢？

https://github.com/apache/dubbo/issues/7054可以看看这个
