### ISSUE TITLE
logging中是否可增加机器相关的信息

### ISSUE THREAD

**Issue by applenele** [dromara/dynamic-tp#291]
logging中是否可增加机器相关的信息，比如主机名或者IP等信息。

**Comment by yanhom1314** [comment]
必要性不大，日志收集器知道在哪台机器，加上相应字段就行了

**Comment by applenele** [comment]
还有个问题，在咨询下， 就是如果 在k8s中 pod的一个日志路径都做了映射到物理机的一个路径，假如在一个机器同一个应用有多个pod，日志都打到这里了${LOG.PATH}/dynamictp/${APP.NAME}.monitor.log，那我如何做区分呢？

**Comment by yanhom1314** [comment]
输出时是可以重命名文件名带上pod信息吧

**Comment by applenele** [comment]
> 输出时是可以重命名文件名带上pod信息吧

这种方式可以。在配置的日志路径的时候动态获取pod名字。如下
spring.dynamic.tp.logPath = /home/app/dtp/${POD_NAME:-demo}
