### ISSUE TITLE
任务执行过程中强转DtpRunable失败

### ISSUE THREAD

**Issue by leohou0430** [dromara/dynamic-tp#292]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：1.8
- SpringBoot版本：2.2.6.RELEASE
- DynamicTp版本：1.1.3
- 配置中心版本：

### 问题描述

文字描述、截图、粘代码方式
- <b>master分支上面代码有校验Runnable类型，在maven仓库中最新的1.1.3版本并没有判断</b>
![image](https://github.com/dromara/dynamic-tp/assets/3467826/a8ccc67e-ce1e-4436-bc17-2439528bbb55)
![image](https://github.com/dromara/dynamic-tp/assets/3467826/01a94949-58b9-4a7c-9e65-50283d172470)

**Comment by KamToHung** [comment]
下个版本发布后会有此判断，1.1.3发布之前遗留了问题

**Comment by leohou0430** [comment]
> 1.1.3发布的时候无此判断

下次什么时候发版？

**Comment by yanhom1314** [comment]
这个月会发，你是使用了什么agent吗？
