### ISSUE TITLE
监控的采集类型是不是添加 jmx 的实现

### ISSUE THREAD

**Issue by liulei0903** [dromara/dynamic-tp#301]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
1、当前监控数据采集器类型（logging | micrometer | internal_logging），默认micrometer，我想添加一个 jmx 采集器

### 应用场景
 jmx 的通用性更强，目前 micrometer 必须依赖 prometheus

**Comment by yanhom1314** [comment]
这个想法不错，可以搞下

**Comment by KamToHung** [comment]
![image](https://github.com/dromara/dynamic-tp/assets/16450524/40c368e8-c772-4ab3-a2f8-5586d0686005)
实现效果
