### ISSUE TITLE
接下来会提供rest接口，修改核心参数吗

### ISSUE THREAD

**Issue by fengzhenbing** [dromara/dynamic-tp#31]
你好
> 接下来会提供rest接口，修改核心参数，同步到配置中心，从而动态改变线程池配置吗

这样就可以定制前端页面去修改了。

**Comment by lyh200** [comment]
这个就相当于自己部署了个server实现配置存储修改推送，要做的话不止要提供一个修改的接口，还得有一个服务启动拉去线程池配置的接口，有想法我们可以探讨下

**Comment by lyh200** [comment]
这个感觉实用性有点不是那么强啊，用配置中心了就直接在配置中心修改呗，都有控制台，也不复杂，要弄这功能还得适配各个配置中心同步，复杂度也不低

**Comment by fengzhenbing** [comment]
> 这个感觉实用性有点不是那么强啊，用配置中心了就直接在配置中心修改呗，都有控制台，也不复杂，要弄这功能还得适配各个配置中心同步，复杂度也不低

是的
