### ISSUE TITLE
依赖版本问题

### ISSUE THREAD

**Issue by axin3892** [dromara/dynamic-tp#316]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 使用方面
能否出一个spring2.x版本和Prometheus之间版本对应的关系，因为在使用的过程中无法找到合适的micrometer-registry-prometheus版本而导致服务无法上报监控，但服务整体没有明显报错，无法确定版本，一旦更换低版本Prometheus，服务直接报错。

我采用了如下依赖
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
            <version>1.7.7</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>1.8.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator</artifactId>
            <version>${spring-boot-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator-autoconfigure</artifactId>
            <version>${spring-boot-version}</version>
        </dependency>

<spring-version>5.1.18.RELEASE</spring-version>
<spring-boot-version>2.1.18.RELEASE</spring-boot-version>
### 其他

**Comment by yanhom1314** [comment]
不用指定版本啊，用springboot管理的版本就行
