### ISSUE TITLE
lark报警平台配置信息【question】

### ISSUE THREAD

**Issue by axin3892** [dromara/dynamic-tp#328]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 使用方面
![image](https://github.com/dromara/dynamic-tp/assets/52096123/7d45c9fe-424a-4f4c-9e1b-a1ed8b367ac3)
请问下，飞书报警配置的receivers项应该填用户的哪个飞书信息，我试过飞书用户id，姓名，姓名的拼音，英文名等，报警信息at的人都没法映射到一个真实的飞书用户上，只是一个字符串

### 其他

**Comment by KamToHung** [comment]
接收人飞书名称
