### ISSUE TITLE
线程池活跃度是否支持指定时间段小于某阈值告警

### ISSUE THREAD

**Issue by comeCU** [dromara/dynamic-tp#334]
### 使用方面
监控线程池在工作时间，预期活跃度较高的情况下，出现异常等情况导致活跃度较低或活跃度为0。

**Comment by KamToHung** [comment]
有run_timeout、queue_timeout、reject告警，出现异常的话是否先检查服务为主

**Comment by comeCU** [comment]
有一个这样的场景：
服务发布或重启，导致我的某些个线程断掉了，线程池活跃线程为0.此时我想收到一些告警。

> 有run_timeout、queue_timeout、reject告警，出现异常的话是否先检查服务为主

**Comment by comeCU** [comment]
有一个这样的场景：
服务发布或重启，导致我的某些个线程断掉了，线程池活跃线程为0.此时我想收到一些告警。

**Comment by yanhom1314** [comment]
> 有一个这样的场景： 服务发布或重启，导致我的某些个线程断掉了，线程池活跃线程为0.此时我想收到一些告警。
> 
> > 有run_timeout、queue_timeout、reject告警，出现异常的话是否先检查服务为主

服务发布重启会停掉线程池，正常流程啊，如果你想在线程池被关闭前做一些告警，可以基于Aware扩展在shutdown前做
