### ISSUE TITLE
升级到1.1.4之后打印的线程统计信息错误

### ISSUE THREAD

**Issue by applenele** [dromara/dynamic-tp#336]
### 使用方面
使用1.1.3.2 打印的线程日志如下
<img width="540" alt="image" src="https://github.com/dromara/dynamic-tp/assets/5456023/de42be69-47c9-48bc-84fc-359e8a86792a">

但是升级到1.1.4之后打印的线程日志如下
<img width="503" alt="image" src="https://github.com/dromara/dynamic-tp/assets/5456023/c9615c53-b74b-4cd3-8ecb-823c89cdb29a">

**Comment by applenele** [comment]
@KamToHung 是不是框架的问题，还是可能我配置的问题？

**Comment by KamToHung** [comment]
> @KamToHung 是不是框架的问题，还是可能我配置的问题？

框架最近优化有些场景没考虑到，应该不是配置问题

**Comment by yanhom1314** [comment]
运行有报啥错误吗，线程池模式是用的eager吗

**Comment by applenele** [comment]
> 运行有报啥错误吗，线程池模式是用的eager吗

没有报错 fixed 模式

**Comment by applenele** [comment]
> 运行有报啥错误吗，线程池模式是用的eager吗

没有报错 fixed 模式

**Comment by applenele** [comment]
> 运行有报啥错误吗，线程池模式是用的eager吗
dubbo 版本2.6.5  springboot 版本2.5.10

**Comment by applenele** [comment]
升级到1.1.5 还是同样的问题，看下是啥原因

**Comment by yanhom1314** [comment]
1.1.6 已修复
