### ISSUE TITLE
Springboot2.0+包依赖问题

### ISSUE THREAD

**Issue by curryQin** [dromara/dynamic-tp#341]
### 使用方面
配置中心：无
Dynamic-tp maven 版本：
<dependency>
			<groupId>org.dromara.dynamictp</groupId>
			<artifactId>dynamic-tp-spring-boot-starter-common</artifactId>
			<version>1.1.4</version>
		</dependency>
报错：
![image](https://github.com/dromara/dynamic-tp/assets/40856266/98f347e7-995e-4856-8508-df937ae3ec0c)
我看springboot 2.0+版本之后已经不依赖这个类，dynamic-tp是不支持springboot 2.0+版本嘛？

### 其他

**Comment by yanhom1314** [comment]
支持啊，dynamictp 没强依赖这个类，在1.x下才会用到这个类

**Comment by curryQin** [comment]
是别的导致的 我已经搞定了 感谢
