### ISSUE TITLE
1.1.4 版本使用@DynamicTp 注解的普通 juc 线程池被shutdown，导致通过@Autowired 注入的线程池无法执行任务，且无任何报错

### ISSUE THREAD

**Issue by TOPG1994** [dromara/dynamic-tp#354]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：1.8.1
- SpringBoot版本：2.4.13
- DynamicTp版本：1.1.4
- 配置中心版本：未使用注册中心

### 问题描述

使用@DynamicTp 注解的普通 juc 线程池被shutdown，导致通过@Autowired 注入的线程池无法执行任务，且无任何报错。

代码路径：
DtpPostProcessor#postProcessAfterInitialization --》 DtpPostProcessor#registerCommon
![image](https://github.com/dromara/dynamic-tp/assets/19574020/c94b2907-52c6-46f3-bbb1-c0d42fe41bab)
![image](https://github.com/dromara/dynamic-tp/assets/19574020/a23561b4-1195-4fc2-8739-e2554e866067)

- 猜测可能原因：
new ThreadPoolExecutorProxy 时，关闭了原始线程池

**Comment by yanhom1314** [comment]
1.1.5版本修复了该bug，升级试试

**Comment by TOPG1994** [comment]
1.1.5 是好的  还想问下，没有其他地方有类似的处理吧 这种影响蛮大的，本来我们只想监控线程池，却反而线程池直接”无声“down掉了

**Comment by yanhom1314** [comment]
shutdown 原始线程池，会重新生成一个新的代理线程池，dynamictp高级特性都是基于代理的做的
