### ISSUE TITLE
【refactor】重构apollo配置变动监听器ApolloRefresher

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#364]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述

目前ApolloRefresher需要在配置里指定对应线程池配置的namespace，有一定的使用复杂度，也不是很优雅。希望对此进行重构，可以通过实现ConfigChangeListener接口来监听所有的namespace的变动（参考AutoUpdateConfigChangeListener），这样就不用单独配置线程池的namespace了

### 应用场景
降低用apollo存储线程池配置的使用难度
### 难度风险
低
### 外部依赖
无

**Comment by thenextsupersun** [comment]
AutoUpdateConfigChangeListener在什么位置

**Comment by BanTanger** [comment]
我比较感兴趣，可以指派给我吗

**Comment by yanhom1314** [comment]
> 我比较感兴趣，可以指派给我吗

已指派
