### ISSUE TITLE
alibaba dubbo adapter 初始化时shutdown原线程池，创建的proxy线程池没生效

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#367]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- DynamicTp版本：1.1.4+

### 问题描述

alibaba dubbo 内部获取线程池没有通过DataStore扩展spi，所以在dynamictp适配器初始化时将dubbo原生线程池shutdown后，新创建的proxy线程池不会生效，他内部会用默认的SHARED_EXECUTOR
![image](https://github.com/dromara/dynamic-tp/assets/13051908/c1eac790-2774-4506-ae1f-2bbb629bbcf4)
![image](https://github.com/dromara/dynamic-tp/assets/13051908/d1e47bb0-5e88-4689-95ba-6679c5dedf56)

### 解决方案
可通过dubbo spi扩展获取Dispatcher对象，然后反射设置内部 executor

**Comment by thenextsupersun** [comment]
图片上的代码在什么路径

**Comment by yanhom1314** [comment]
> 可通过dubbo spi扩展获取Dispatcher对象,但是如何获取WrappedChannelHandler对象，线程池是在WrappedChannelHandler中。 @yanhom1314
> 
> ![image](https://private-user-images.githubusercontent.com/5456023/287213269-d0107171-cab0-42a5-b377-14c5948767d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjM3NzgsIm5iZiI6MTcwMTQyMzQ3OCwicGF0aCI6Ii81NDU2MDIzLzI4NzIxMzI2OS1kMDEwNzE3MS1jYWIwLTQyYTUtYjM3Ny0xNGM1OTQ4NzY3ZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDkzNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc3MDM3MDYzNjQ5ZWI4N2VmNDc1OWMxNmZhYTAwOTZhZDBjMzg3N2ZkNjcyOWFjNTFkMmE1MjhmNmRlYThhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7d-LzKJfJUYhz3WUOC1PicfcNNNcf4OouMbN2ZvBHVE)

AllChannelHandler 是继承 WrappedChannelHandler 的吧

**Comment by applenele** [comment]
![image](https://github.com/dromara/dynamic-tp/assets/5456023/90eda8b7-6990-4265-8d4f-09b93d6bfac9)

仔细看了下，executorMap.replace(k, proxy)  dataStore元数据不会修改，建议用dataStore put覆盖的方式试试。

@yanhom1314

**Comment by applenele** [comment]
> > 可通过dubbo spi扩展获取Dispatcher对象,但是如何获取WrappedChannelHandler对象，线程池是在WrappedChannelHandler中。 @yanhom1314
> > ![image](https://private-user-images.githubusercontent.com/5456023/287213269-d0107171-cab0-42a5-b377-14c5948767d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjM3NzgsIm5iZiI6MTcwMTQyMzQ3OCwicGF0aCI6Ii81NDU2MDIzLzI4NzIxMzI2OS1kMDEwNzE3MS1jYWIwLTQyYTUtYjM3Ny0xNGM1OTQ4NzY3ZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDkzNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc3MDM3MDYzNjQ5ZWI4N2VmNDc1OWMxNmZhYTAwOTZhZDBjMzg3N2ZkNjcyOWFjNTFkMmE1MjhmNmRlYThhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7d-LzKJfJUYhz3WUOC1PicfcNNNcf4OouMbN2ZvBHVE)
> 
> AllChannelHandler 是继承 WrappedChannelHandler 的吧

是的

**Comment by yanhom1314** [comment]
> ![image](https://private-user-images.githubusercontent.com/5456023/287227440-fd25c1d3-7b52-463e-bd75-e7625fa91593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2MTksIm5iZiI6MTcwMTQyNDMxOSwicGF0aCI6Ii81NDU2MDIzLzI4NzIyNzQ0MC1mZDI1YzFkMy03YjUyLTQ2M2UtYmQ3NS1lNzYyNWZhOTE1OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDk1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJlYzA3ZjM1NzYwYWQ3YzRlNmM5MjY2NDAzNTU4ZjgyOTExZTcwYjIwOGZmYjE3ZmRhNWFjYjlmMTYzMjhmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mEt_eXculPo6B-Fr4zikaPqCjU_5XJdkvSktT_b3vDg)
> 
> 仔细看了下 dataStore.get() 返回的一个新Map，executorMap.replace(k, proxy) dataStore元数据不会修改，建议用dataStore put覆盖的方式试试。 ![image](https://private-user-images.githubusercontent.com/5456023/287226261-90eda8b7-6990-4265-8d4f-09b93d6bfac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2MTksIm5iZiI6MTcwMTQyNDMxOSwicGF0aCI6Ii81NDU2MDIzLzI4NzIyNjI2MS05MGVkYThiNy02OTkwLTQyNjUtOGQ0Zi0wOWI5M2Q2YmZhYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDk1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQwYTE2N2Y0Y2EyZTkzYjBhMzU5ZGRkMDdmYWZjZmI4MGE0MGZlN2QxMjk4NmVjODM1MGE5ODMxOTc4ZTMzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cx1e8za8aLlem2o12QgaJhQGq4O92ofB3c2F9kOoX0M)
> 
> @yanhom1314
> 
> 另外建议排查下Apache Dubbo

有可能是这个问题，apache dubbo 高版本是通过反射获取data的，应该没问题，低版本也可能有这个问题，你有dubbo环境，改完测测吧

**Comment by applenele** [comment]
> > ![image](https://private-user-images.githubusercontent.com/5456023/287227440-fd25c1d3-7b52-463e-bd75-e7625fa91593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2MTksIm5iZiI6MTcwMTQyNDMxOSwicGF0aCI6Ii81NDU2MDIzLzI4NzIyNzQ0MC1mZDI1YzFkMy03YjUyLTQ2M2UtYmQ3NS1lNzYyNWZhOTE1OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDk1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJlYzA3ZjM1NzYwYWQ3YzRlNmM5MjY2NDAzNTU4ZjgyOTExZTcwYjIwOGZmYjE3ZmRhNWFjYjlmMTYzMjhmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mEt_eXculPo6B-Fr4zikaPqCjU_5XJdkvSktT_b3vDg)
> > 仔细看了下 dataStore.get() 返回的一个新Map，executorMap.replace(k, proxy) dataStore元数据不会修改，建议用dataStore put覆盖的方式试试。 ![image](https://private-user-images.githubusercontent.com/5456023/287226261-90eda8b7-6990-4265-8d4f-09b93d6bfac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2MTksIm5iZiI6MTcwMTQyNDMxOSwicGF0aCI6Ii81NDU2MDIzLzI4NzIyNjI2MS05MGVkYThiNy02OTkwLTQyNjUtOGQ0Zi0wOWI5M2Q2YmZhYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDk1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQwYTE2N2Y0Y2EyZTkzYjBhMzU5ZGRkMDdmYWZjZmI4MGE0MGZlN2QxMjk4NmVjODM1MGE5ODMxOTc4ZTMzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cx1e8za8aLlem2o12QgaJhQGq4O92ofB3c2F9kOoX0M)
> > @yanhom1314
> > 另外建议排查下Apache Dubbo
> 
> 有可能是这个问题，apache dubbo 高版本是通过反射获取data的，应该没问题，低版本也可能有这个问题，你有dubbo环境，改完测测吧

不行，不能这么整，还是得想办法替换WrappedChannelHandler中的executor

**Comment by ray-lsr** [comment]
扩展方式可以实现，不过dispatcher有5个实现，虽然all是最常用的，但是扩展后，必须配置扩展后的id如图
<img width="536" alt="image" src="https://github.com/dromara/dynamic-tp/assets/45811620/a2310bc4-6de8-4caa-bf8e-2403d2b687db">

**Comment by yanhom1314** [comment]
@applenele @ray-lsr 不好直接获取到的话可以用 jvmti 工具，能直接获取到内存中指定类的对象

**Comment by ray-lsr** [comment]
@yanhom1314 使用jvmti==agent了，那使用项目还要 -javaagent这不太好吧
