### ISSUE TITLE
undertow线程池管理报java.lang.VerifyError: Cannot inherit from final class异常

### ISSUE THREAD

**Issue by yiyi910** [dromara/dynamic-tp#376]
- Jdk版本：1.8
- SpringBoot版本：2.7.18
- DynamicTp版本：1.1.6.1
- 配置中心版本：无配置中心接入

### 问题描述
管理undertow 线程池报java.lang.verifyerror: cannot inherit from final class异常

pom.xml依赖：
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-undertow</artifactId>
</dependency>
<dependency>
    <groupId>org.dromara.dynamictp</groupId>
    <artifactId>dynamic-tp-spring-boot-starter-adapter-webserver</artifactId>
    <version>1.1.6.1</version>
</dependency>
```

- 配置文件：在内网不方便发
- 代码使用步骤：配好配置文件启动就报错
- 猜测可能原因：管理tomcat跟jetty都没问题，换到undertow就报错，猜测可能dynamic-tp重写了EnhancedQueueExecutor类与undertow依赖的jboss-threads-3.1.0.Final.jar中的类重复导致

**Comment by yanhom1314** [comment]
![image](https://github.com/dromara/dynamic-tp/assets/13051908/36576f03-3d12-4eee-8547-92aa10434078)
有这个日志输出吧，调整下上述两个依赖的顺序

**Comment by yiyi910** [comment]
把
```
<dependency>
    <groupId>org.dromara.dynamictp</groupId>
    <artifactId>dynamic-tp-spring-boot-starter-adapter-webserver</artifactId>
    <version>1.1.6.1</version>
</dependency>
```
放到
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-undertow</artifactId>
</dependency>
```
之前就好了，谢谢

**Comment by DevForJava** [comment]
> 把
> 
> ```
> <dependency>
>     <groupId>org.dromara.dynamictp</groupId>
>     <artifactId>dynamic-tp-spring-boot-starter-adapter-webserver</artifactId>
>     <version>1.1.6.1</version>
> </dependency>
> ```
> 
> 放到
> 
> ```
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-undertow</artifactId>
> </dependency>
> ```
> 
> 之前就好了，谢谢
👍啊，这都能想到

**Comment by 1132032434** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
