### ISSUE TITLE
配置了企业微信推送，邮箱推送。但是无法收到推送消息

### ISSUE THREAD

**Issue by Lindont** [dromara/dynamic-tp#397]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：JDK17
- SpringBoot版本：3.2.2
- DynamicTp版本：1.1.6.1-3.x
- 配置中心版本：无

### 问题描述
配置了企业微信推送，邮箱推送。但是无法收到推送消息。
<img width="1920" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/3ed8f99b-3b1f-4edd-8dde-b075dbbd6c44">

<img width="793" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/f46ac99c-d44f-47d2-a845-2778cd97f38f">

<img width="1243" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/a2a7c91b-a5ef-4edb-b19d-150a578e7c2c">

**Comment by yanhom1314** [comment]
通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？

**Comment by Lindont** [comment]
> 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？

<img width="848" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/83efd442-6213-43c2-b60f-58adb9d7158d">

降低版本了，还是没收到

**Comment by Lindont** [comment]
推送失败的时候，能不能打印点日志出来，不然不知道怎么回事

**Comment by yanhom1314** [comment]
> > 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？
> 
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/16914978/302158338-83efd442-6213-43c2-b60f-58adb9d7158d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzNjgsIm5iZiI6MTcwNzEwMDA2OCwicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNTgzMzgtODNlZmQ0NDItNjIxMy00M2MyLWI2MGYtNThhZGI5ZDcxNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWQ2MDBhOGFiY2Y0NmEyZWNkMDM3YzdiNmFkZmU5OThkZmM5YWNkYzU0YTdmMjlkODJiN2YzNjNmYjFmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sCvZ93Gw7RfNHKg5B7keOe1aF3tGN-DYZ1Kp-0U0Po">
> 降低版本了，还是没收到

没用配置中心？

**Comment by Lindont** [comment]
我测试的是这个
<img width="1209" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/1e75d97b-91d1-433a-9ec7-9d89fb31cce8">

**Comment by Lindont** [comment]
> > > 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？
> > 
> > 
> > <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/16914978/302158338-83efd442-6213-43c2-b60f-58adb9d7158d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzNjgsIm5iZiI6MTcwNzEwMDA2OCwicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNTgzMzgtODNlZmQ0NDItNjIxMy00M2MyLWI2MGYtNThhZGI5ZDcxNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWQ2MDBhOGFiY2Y0NmEyZWNkMDM3YzdiNmFkZmU5OThkZmM5YWNkYzU0YTdmMjlkODJiN2YzNjNmYjFmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sCvZ93Gw7RfNHKg5B7keOe1aF3tGN-DYZ1Kp-0U0Po">
> > 降低版本了，还是没收到
> 
> 没用配置中心？你测的是通知还是告警，你这是还没走到发送步骤，发送失败肯定有日志输出的，调试下吧

没有使用配置中心，这个demo是单体项目

**Comment by yanhom1314** [comment]
> > > > 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？
> > > 
> > > 
> > > <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/16914978/302158338-83efd442-6213-43c2-b60f-58adb9d7158d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzNjgsIm5iZiI6MTcwNzEwMDA2OCwicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNTgzMzgtODNlZmQ0NDItNjIxMy00M2MyLWI2MGYtNThhZGI5ZDcxNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWQ2MDBhOGFiY2Y0NmEyZWNkMDM3YzdiNmFkZmU5OThkZmM5YWNkYzU0YTdmMjlkODJiN2YzNjNmYjFmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sCvZ93Gw7RfNHKg5B7keOe1aF3tGN-DYZ1Kp-0U0Po">
> > > 降低版本了，还是没收到
> > 
> > 
> > 没用配置中心？你测的是通知还是告警，你这是还没走到发送步骤，发送失败肯定有日志输出的，调试下吧
> 
> 没有使用配置中心，这个demo是单体项目

额，没用配置中心你怎么做的动态调参，通知是在监听器里触发的

**Comment by Lindont** [comment]
> > > > > 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？
> > > > 
> > > > 
> > > > <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/16914978/302158338-83efd442-6213-43c2-b60f-58adb9d7158d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzNjgsIm5iZiI6MTcwNzEwMDA2OCwicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNTgzMzgtODNlZmQ0NDItNjIxMy00M2MyLWI2MGYtNThhZGI5ZDcxNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWQ2MDBhOGFiY2Y0NmEyZWNkMDM3YzdiNmFkZmU5OThkZmM5YWNkYzU0YTdmMjlkODJiN2YzNjNmYjFmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sCvZ93Gw7RfNHKg5B7keOe1aF3tGN-DYZ1Kp-0U0Po">
> > > > 降低版本了，还是没收到
> > > 
> > > 
> > > 没用配置中心？你测的是通知还是告警，你这是还没走到发送步骤，发送失败肯定有日志输出的，调试下吧
> > 
> > 
> > 没有使用配置中心，这个demo是单体项目
> 
> 额，没用配置中心你怎么做的动态调参，通知是在监听器里触发的

直接代码改的。还有测试运行超时也没通知。但是看日志是有输出报错了
<img width="674" alt="image" src="https://github.com/dromara/dynamic-tp/assets/16914978/cd0523e8-7dfe-4abf-89d6-8493657420e0">

**Comment by yanhom1314** [comment]
> > > > > > 通知告警相关入口断点调试下看看，springboot3 我们是用3.1测试的，3.2不确定有没有问题，或者你降低下版本试试？
> > > > > 
> > > > > 
> > > > > <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/16914978/302158338-83efd442-6213-43c2-b60f-58adb9d7158d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzNjgsIm5iZiI6MTcwNzEwMDA2OCwicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNTgzMzgtODNlZmQ0NDItNjIxMy00M2MyLWI2MGYtNThhZGI5ZDcxNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWQ2MDBhOGFiY2Y0NmEyZWNkMDM3YzdiNmFkZmU5OThkZmM5YWNkYzU0YTdmMjlkODJiN2YzNjNmYjFmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sCvZ93Gw7RfNHKg5B7keOe1aF3tGN-DYZ1Kp-0U0Po">
> > > > > 降低版本了，还是没收到
> > > > 
> > > > 
> > > > 没用配置中心？你测的是通知还是告警，你这是还没走到发送步骤，发送失败肯定有日志输出的，调试下吧
> > > 
> > > 
> > > 没有使用配置中心，这个demo是单体项目
> > 
> > 
> > 额，没用配置中心你怎么做的动态调参，通知是在监听器里触发的
> 
> 直接代码改的。还有测试运行超时也没通知。但是看日志是有输出报错了 <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/16914978/302160809-cd0523e8-7dfe-4abf-89d6-8493657420e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDEwMzcsIm5iZiI6MTcwNzEwMDczNywicGF0aCI6Ii8xNjkxNDk3OC8zMDIxNjA4MDktY2QwNTIzZTgtN2RmZS00YWJmLTg5ZDYtODQ5MzY1NzQyMGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMzg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZmMzNDFkYzBhOGU1MDc2OTdiYzkxNDJhMzVlYzUyZDIwNTliNTNkZmJhZjVjNTRhYjVjNTM1MThkNmVhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tHpHRKj5zkslhqdJMkrAGh2v0OABmX-vge5wHPhfhgU">

直接改的肯定不行，触发超时告警后 AlarmManager类里断点调试下吧

**Comment by Lindont** [comment]
好的，我调试一下
