### ISSUE TITLE
dubbo 2.7.5以下的版本动态线程池不生效

### ISSUE THREAD

**Issue by piemon-nyah** [dromara/dynamic-tp#400]
### 版本信息

- Jdk版本：1.8
- SpringBoot版本：2.1.18
- DynamicTp版本：1.1.6.1
- 配置中心版本：/

### 问题描述
2.7.5以下的dubbo动态线程池似乎无法生效，org.dromara.dynamictp.adapter.dubbo.apache.ApacheDubboDtpAdapter是将DataStore中的线程池替换成了动态线程池
![image-20240220094555520](https://github.com/dromara/dynamic-tp/assets/50912843/952a141f-8ece-43a9-b169-41f38efb97fb)
但在dubbo 2.7.5以下的版本， org.apache.dubbo.remoting.transport.dispatcher.WrappedChannelHandler#getExecutorService中并不会通过DataStore获取线程池，而是直接用WrappedChannelHandler中的线程池
![image](https://github.com/dromara/dynamic-tp/assets/50912843/22c73e84-7324-43d4-82c9-506d7eb49306)
由于ApacheDubboDtpAdapter中putAndFinalize方法会关闭原始线程池，导致dubbo调用中只能使用SHARED_EXECUTOR
![image](https://github.com/dromara/dynamic-tp/assets/50912843/01eb358c-2942-4c55-9024-81f2740787fa)
![image](https://github.com/dromara/dynamic-tp/assets/50912843/ef543b7b-5b95-447e-882e-2a8be6d7343f)
在2.7.5及以上版本则不会有上述问题， 因为org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository#getExecutor获取线程池会通过data获取
![image](https://github.com/dromara/dynamic-tp/assets/50912843/08038d7e-a7d4-40ac-91d3-6162f3bd1368)
与dynamictp修改的逻辑一致
![image](https://github.com/dromara/dynamic-tp/assets/50912843/50ca6ee4-84eb-4929-876a-1846f316f01a)
 测试只有两个线程执行
![image](https://github.com/dromara/dynamic-tp/assets/50912843/a6bccd0d-8469-4345-998f-00fa97b03f5b)

### 解决方法
考虑获取WrappedChannelHandler对象，直接修改WrappedChannelHandler中的executor，我自己有尝试改一版，可以提交下pr一起看看

**Comment by KamToHung** [comment]
> ### 版本信息
> * Jdk版本：1.8
> * SpringBoot版本：2.1.18
> * DynamicTp版本：1.1.6.1
> * 配置中心版本：/
> 
> ### 问题描述
> 2.7.5以下的dubbo动态线程池似乎无法生效，org.dromara.dynamictp.adapter.dubbo.apache.ApacheDubboDtpAdapter是将DataStore中的线程池替换成了动态线程池 ![image-20240220094555520](https://private-user-images.githubusercontent.com/50912843/306114126-952a141f-8ece-43a9-b169-41f38efb97fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMTQxMjYtOTUyYTE0MWYtOGVjZS00M2E5LWIxNjktNDFmMzhlZmI5N2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZjNmMmMwNjY4MGEyNjFmYTc1NWY3N2IzOWYzYTkzNjljY2QzYmRkNzNiYWExYTE2N2JjZDQ1YjFmYTQ5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X-9CwtzHDKLkyjSHpcblsG9daYRVhYsyBQ3TLQmsVuA) 但在dubbo 2.7.5以下的版本， org.apache.dubbo.remoting.transport.dispatcher.WrappedChannelHandler#getExecutorService中并不会通过DataStore获取线程池，而是直接用WrappedChannelHandler中的线程池 ![image](https://private-user-images.githubusercontent.com/50912843/306115342-22c73e84-7324-43d4-82c9-506d7eb49306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMTUzNDItMjJjNzNlODQtNzMyNC00M2Q0LTgyYzktNTA2ZDdlYjQ5MzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZDQ1ZWQxYTU5ZTE2NDU1ZDI4NjU2YTkwZDQ5ZGMxNTU3OWZlYjg3MTcwOTE2ZGM5OWQ4MzZjZjMwODQ0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDcaSp3ql7v9K7IYtNKYQFxf6MOoz9mNy5JmRxpuCX4) 由于ApacheDubboDtpAdapter中putAndFinalize方法会关闭原始线程池，导致dubbo调用中只能使用SHARED_EXECUTOR ![image](https://private-user-images.githubusercontent.com/50912843/306118525-01eb358c-2942-4c55-9024-81f2740787fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMTg1MjUtMDFlYjM1OGMtMjk0Mi00YzU1LTkwMjQtODFmMjc0MDc4N2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZDExNjY0ZmVhMDA2NDgzYTc4MWQ5NTQ3ODI2ODhkZjA1OTM5MWNiOTQxNmQ0NGQ1NjNjMzc0NjY5YTYwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ni5xNWmZRTfEyaQAFMhwxW6HMvLP1S9lJ7ZwS68o508) ![image](https://private-user-images.githubusercontent.com/50912843/306118684-ef543b7b-5b95-447e-882e-2a8be6d7343f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMTg2ODQtZWY1NDNiN2ItNWI5NS00NDdlLTg4MmUtMmE4YmU2ZDczNDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYTA5NjE0NDdlM2ZjMDAxNDkzZTJlMTFiMmJlMTRiOGNjNDFkZGUyM2FhMmRmYjU3NmYzODA0MDg5ZTEwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPFffy2PjOwfBp9Eu2QNFk4eNi4CzXUG7pSwD12NZsI) 在2.7.5及以上版本则不会有上述问题， 因为org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository#getExecutor获取线程池会通过data获取 ![image](https://private-user-images.githubusercontent.com/50912843/306119711-08038d7e-a7d4-40ac-91d3-6162f3bd1368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMTk3MTEtMDgwMzhkN2UtYTdkNC00MGFjLTkxZDMtNjE2MmYzYmQxMzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Yzc2MjMwYjNlYTM5OTM1N2QwMmYwMDY3ZDU1Y2M0NWIzZWEyYTBiZDAzNzYwZjA0Mzg0M2JjYzBkNWUxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEtYoOcoqM9nLfLh6xy2AdE33IsHX8sAgjOxMwnZaMs) 与dynamictp修改的逻辑一致 ![image](https://private-user-images.githubusercontent.com/50912843/306120098-50ca6ee4-84eb-4929-876a-1846f316f01a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMjAwOTgtNTBjYTZlZTQtODRlYi00OTI5LTg3NmEtMTg0NmYzMTZmMDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NGM1NmNmODRkMWU2YjQxMTM2MzBhODk1MzEwZmM2NmY4NDM3MzU2OTkxNzQwZDMxMjc2NjdhM2FkYTdkNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c7dyVACuXoo1mS0PZ3RyNEf4gkrQE5G4Cq1-0JxZRdg) 测试只有两个线程执行 ![image](https://private-user-images.githubusercontent.com/50912843/306123665-a6bccd0d-8469-4345-998f-00fa97b03f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE5NjYsIm5iZiI6MTcwODQwMTY2NiwicGF0aCI6Ii81MDkxMjg0My8zMDYxMjM2NjUtYTZiY2NkMGQtODQ2OS00MzQ1LTk5OGYtMDBmYTk3YjAzZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDc1Y2IxMDczYjkwMDNkMTQ2ZmJkZDNiNWMxNjhkZTliMmM5NWQyNjQ1YjRkNDFhMTgzOTNhOTY3YTMwOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGP5nsNkXez_Y34E8W8Z6SdL02e3-boXo4MQJn-64vs)
> 
> ### 解决方法
> 考虑获取WrappedChannelHandler对象，直接修改WrappedChannelHandler中的executor，我自己有尝试改一版，可以提交下pr一起看看

好，指派给你了
