### ISSUE TITLE
[type: new feature] support MemorySafeLinkedBlockingQueue

### ISSUE THREAD

**Issue by dragon-zhang** [dromara/dynamic-tp#41]
see https://github.com/apache/dubbo/pull/10021

**Comment by lyh200** [comment]
LGTM, you can make a pull request for this new feature old brother.

**Comment by dragon-zhang** [comment]
> LGTM, you can make a pull request for this new feature old brother.

sure, brother, after dubbo merged.

**Comment by lyh200** [comment]
merged，thank you brother！
