### ISSUE TITLE
1.1.6.1版本和Skywalking线程池插件使用内存溢出

### ISSUE THREAD

**Issue by cqxing** [dromara/dynamic-tp#411]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：1.8
- SpringBoot版本：2.7.18
- SpringCloud版本：2021.0.8
- DynamicTp版本：1.1.6.1
- 配置中心版本：Nacos2.2.1
- Skywalking版本：9.5.0
- Skywalking Agent版本：8.16.0

### 问题描述

文字描述、截图、粘代码方式

- 配置文件：

- 代码使用步骤：
1.项目引用jar包
<dependency>
            <groupId>org.dromara.dynamictp</groupId>
            <artifactId>dynamic-tp-spring-cloud-starter-nacos</artifactId>
        </dependency> 

2.Skywalking Agent
将bootstrap-plugins/apm-jdk-threadpool-plugin-8.16.0.jar挪到plugins/apm-jdk-threadpool-plugin-8.16.0.jar
 

3.spring boot服务运行两个时刻dump文件对比
![IMG20240228-165421](https://github.com/dromara/dynamic-tp/assets/13995998/306740af-f29b-4f19-9bca-155a04fe4dcb)
 

- 报错信息：
服务内存一直不断变大，GC也没有用，无法回收对象
- 猜测可能原因：

### 复现步骤

1. xxx
2. xxx

### 其他信息

1. xxx
2. xxx

**Comment by yanhom1314** [comment]
引入这个包 试试dynamic-tp-extension-skywalking

**Comment by cqxing** [comment]
> 引入这个包试试dynamic-tp-extension-skywalking

<dependency>
    <groupId>cn.dynamictp</groupId>
    <artifactId>dynamic-tp-extension-skywalking</artifactId>
    <version>1.1.2</version>
</dependency>

引了这个包，没有改善

**Comment by yanhom1314** [comment]
> > 引入这个包试试dynamic-tp-extension-skywalking
> 
> <dependency>
>     <groupId>cn.dynamictp</groupId>
>     <artifactId>dynamic-tp-extension-skywalking</artifactId>
>     <version>1.1.2</version>
> </dependency>
> 
> 引了这个包，没有改善

用1.1.6.1啊

**Comment by cqxing** [comment]
> > > 引入这个包试试dynamic-tp-extension-skywalking
> > 
> > 
> > 
> >     cn.dynamictp
> >     dynamic-tp-extension-skywalking
> >     1.1.2
> > 
> > 引了这个包，没有改善
> 
> 用1.1.6.1啊

**Comment by cqxing** [comment]
用了1.1.6.1 dynamic-tp-extension-skywalking  没问题了
