### ISSUE TITLE
大佬们可以提供下grafana监控模版json或者id吗

### ISSUE THREAD

**Issue by fattyliu** [dromara/dynamic-tp#416]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 其他

**Comment by 1132032434** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fattyliu** [comment]
找到了 项目里面有 谢谢
