### ISSUE TITLE
飞书报警 填写了username(非openid的情况),  发出的消息接受人为空

### ISSUE THREAD

**Issue by fattyliu** [dromara/dynamic-tp#428]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。

### 其他

**Comment by fattyliu** [comment]
public static final String LARK_AT_FORMAT_USERNAME = "<at id=''>%s</at>";
 
 id = '' 导致的

**Comment by KamToHung** [comment]
> ```
> public static final String LARK_AT_FORMAT_USERNAME = "<at id=''>%s</at>";
> ```
> 
> id = '' 导致的, 增加空格或者其他内容 都可以

谢谢提出，已修正
