### ISSUE TITLE
钉钉告警@所有人不生效

### ISSUE THREAD

**Issue by Humsen** [dromara/dynamic-tp#439]
### 版本信息

- Jdk版本：1.8
- DynamicTp版本：1.1.7

### 问题描述

钉钉@所有人的字段是[isAtAll]，这里源码使用基本类型，导致序列化后没有了is前缀。

<img width="826" alt="image" src="https://github.com/user-attachments/assets/4a4bfed1-1221-4262-8abf-b76cc6ae688e">

- 猜测可能原因：

将ji基本类型改为包装类即可

<img width="913" alt="image" src="https://github.com/user-attachments/assets/4a26a878-1813-44f9-b64f-1e8fdddbb6af">

### 复现步骤

直接调用JsonUtil.toJson(markdownReq)即可复现

**Comment by yanhom1314** [comment]
感谢反馈，可以提个pr修复下
