### ISSUE TITLE
添加全局配置，减少配置量 

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#443]
**首先感谢您使用 DynamicTp，如果对项目有好的想法建议，请按照下述模板提议讨论，建议使用 Markdown 语法**。

### 方案描述
配置文件添加全局配置 global项，如果线程池层面没做字段覆盖，则用全局配置

![image](https://github.com/user-attachments/assets/93f7db0f-59b6-451a-ac72-9d0d8b25242a)
线程池配置有很多，如果项目中有多个线程池，有差异的一般在线程池名、核心线程数、最大线程数、队列大小这些，其他很多项可能都是一样的，就可以将这些相同的配置项提取到global下，所有线程池共用，减少配置量，线程池自己也可以覆盖全局项
### 应用场景
多个线程池参数都相同的情况减少配置量
### 难度风险
低
### 外部依赖
无

**Comment by TheFatRatre** [comment]
可以把这个分配给我吗

**Comment by yanhom1314** [comment]
> 可以把这个分配给我吗

指给你了

**Comment by DimonHo** [comment]
spring 配置项没有提示啊，都不知道那些配置是可以全局生效的。
![image](https://github.com/user-attachments/assets/2204fdc1-a467-4805-b65f-acc8feb8e5ea)

**Comment by TheFatRatre** [comment]
> spring 配置项没有提示啊，都不知道那些配置是可以全局生效的。 ![image](https://private-user-images.githubusercontent.com/3371641/383069571-2204fdc1-a467-4805-b65f-acc8feb8e5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTg2NjUsIm5iZiI6MTczMDc5ODM2NSwicGF0aCI6Ii8zMzcxNjQxLzM4MzA2OTU3MS0yMjA0ZmRjMS1hNDY3LTQ4MDUtYjY1Zi1hY2M4ZmViOGU1ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDkxOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc0ZGY5YWZlNjNhMGQyMzdiMzhhYTkyOWJiMTc1Y2VmZWI4YWNmZGE0MTI0NmRlODAxNmViYzhkMzA0ZDUzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NJv3cP9cVTtj2k3WMkzbIWd7j5EGUdUd9KD23B6rczM)

设计最上面已经说了啊，除了需要动态改变的核心参数其他的都可以用全局变量进行配置，这是正确的使用方式

**Comment by KamToHung** [comment]
> spring 配置项没有提示啊，都不知道那些配置是可以全局生效的。 ![image](https://private-user-images.githubusercontent.com/3371641/383069571-2204fdc1-a467-4805-b65f-acc8feb8e5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTk3NDYsIm5iZiI6MTczMDc5OTQ0NiwicGF0aCI6Ii8zMzcxNjQxLzM4MzA2OTU3MS0yMjA0ZmRjMS1hNDY3LTQ4MDUtYjY1Zi1hY2M4ZmViOGU1ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDkzNzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI5M2VjYTM0ZTE0OTVhYzkzOTFkOGMzYWFhODI1NmMwNTJkMTI0NTc2YzEwN2NkNzI0YjQyNmRlMjhjZTdhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tB78xpyDKntc4MUg_DLk_tfv6izgluJWMWPSvVbMalk)

有一版我们为了适配spring mvc，配置移除了部分对spring-boot的引用，所以点击yml属性不再会跳转，可以通过官网和配置文件代码等途径配置下

**Comment by KamToHung** [comment]
> > spring 配置项没有提示啊，都不知道那些配置是可以全局生效的。 ![image](https://private-user-images.githubusercontent.com/3371641/383069571-2204fdc1-a467-4805-b65f-acc8feb8e5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTg2NjUsIm5iZiI6MTczMDc5ODM2NSwicGF0aCI6Ii8zMzcxNjQxLzM4MzA2OTU3MS0yMjA0ZmRjMS1hNDY3LTQ4MDUtYjY1Zi1hY2M4ZmViOGU1ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDkxOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc0ZGY5YWZlNjNhMGQyMzdiMzhhYTkyOWJiMTc1Y2VmZWI4YWNmZGE0MTI0NmRlODAxNmViYzhkMzA0ZDUzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NJv3cP9cVTtj2k3WMkzbIWd7j5EGUdUd9KD23B6rczM)
> 
> 设计最上面已经说了啊，除了需要动态改变的核心参数其他的都可以用全局变量进行配置，这是正确的使用方式

使用spring-boot-configuration-processor或者手动修改下 starter/starter-common/src/main/resources/META-INF/additional-spring-configuration-metadata.json 即可提示

> spring 配置项没有提示啊，都不知道那些配置是可以全局生效的。 ![image](https://private-user-images.githubusercontent.com/3371641/383069571-2204fdc1-a467-4805-b65f-acc8feb8e5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDI3MTUsIm5iZiI6MTczMDgwMjQxNSwicGF0aCI6Ii8zMzcxNjQxLzM4MzA2OTU3MS0yMjA0ZmRjMS1hNDY3LTQ4MDUtYjY1Zi1hY2M4ZmViOGU1ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTAyNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRjZTQ3MDk4YjVkZjY1NGQyNjJhZGE2ZDM1YjZjMWI0ZjE5NDJjOTFlMTA3MjUzMzdiNWYyODY0Yzc4YmFlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VcdarlR8cGP0Q7XttFSWkkFY6gvWCe0HhgcbEUWoLrc)

待下版本修改dditional-spring-configuration-metadata.json后会有提示，现在需要看看文档或者配置的类
