### ISSUE TITLE
dubbo 线程池管理疑问

### ISSUE THREAD

**Issue by chenzhihao1040728129** [dromara/dynamic-tp#457]
**首先感谢作者**。

### 使用方面
> 如果dubbo端口配置的是 "-1"  应用运行寻找可用端口情况下,  dynamic-tp怎么配置?
dubbo版本2.7.8

如图
![image](https://github.com/user-attachments/assets/a0ebb688-99b1-4783-ac5e-fb9af4230385)

我这样配置好像不生效
![image](https://github.com/user-attachments/assets/46a4ed2d-8106-457c-931d-7960ca39cf5d)

**Comment by chenzhihao1040728129** [comment]
从我本地运行项目是能使用默认端口的
![image](https://github.com/user-attachments/assets/098d0d18-8469-47ea-901e-c8c89bfd72c0)

但是测试环境从监控数据来看获取的不是默认端口
![image](https://github.com/user-attachments/assets/687285f8-c8e1-495e-873e-784cdeaf9f5f)

**Comment by chenzhihao1040728129** [comment]
![image](https://github.com/user-attachments/assets/2f4cc93c-21d4-4e12-8208-ad995860555f)
目前我能想到的解决方案, 不知道有没有什么风险点

**Comment by yanhom1314** [comment]
服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢

**Comment by chenzhihao1040728129** [comment]
> 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
如果不能提前知道端口呢

**Comment by yanhom1314** [comment]
> > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > 如果不能提前知道端口呢

就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称

**Comment by chenzhihao1040728129** [comment]
> > > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > > 如果不能提前知道端口呢
> 
> 就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称

对了忘记说,  目前公司没有使用配置中心,  目前集成方式是使用无配置中心方式集成

**Comment by yanhom1314** [comment]
> > > > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > > > 如果不能提前知道端口呢
> > 
> > 
> > 就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称
> 
> 对了忘记说, 目前公司没有使用配置中心, 目前集成方式是使用无配置中心方式集成

那为啥不指定端口呢，又想配置文件里配置线程池名称，又不能事先知道端口，这不矛盾，提高复杂度么

**Comment by chenzhihao1040728129** [comment]
> > > > > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > > > > 如果不能提前知道端口呢
> > > 
> > > 
> > > 就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称
> > 
> > 
> > 对了忘记说, 目前公司没有使用配置中心, 目前集成方式是使用无配置中心方式集成
> 
> 那为啥不指定端口呢，又想配置文件里配置线程池名称，又不能事先知道端口，这不矛盾，提高复杂度么

公司历史遗留问题,  我也是刚进公司不久, 估计生产环境出现过端口冲突启动失败, 我按我上述代码实现先把

**Comment by yanhom1314** [comment]
> > > > > > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > > > > > 如果不能提前知道端口呢
> > > > 
> > > > 
> > > > 就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称
> > > 
> > > 
> > > 对了忘记说, 目前公司没有使用配置中心, 目前集成方式是使用无配置中心方式集成
> > 
> > 
> > 那为啥不指定端口呢，又想配置文件里配置线程池名称，又不能事先知道端口，这不矛盾，提高复杂度么
> 
> 公司历史遗留问题, 我也是刚进公司不久, 估计生产环境出现过端口冲突启动失败, 我按我上述代码实现先把

dubbo支持多协议，多端口的，上述代码会有问题的

**Comment by chenzhihao1040728129** [comment]
> > > > > > > 服务启动日志里有输出dubbo线程池名称，可以在日志里找然后配置在配置中心上呢
> > > > > > > 如果不能提前知道端口呢
> > > > > 
> > > > > 
> > > > > 就是不能提前知道情况下，通过线程池注册时的日志拿线程池名称
> > > > 
> > > > 
> > > > 对了忘记说, 目前公司没有使用配置中心, 目前集成方式是使用无配置中心方式集成
> > > 
> > > 
> > > 那为啥不指定端口呢，又想配置文件里配置线程池名称，又不能事先知道端口，这不矛盾，提高复杂度么
> > 
> > 
> > 公司历史遗留问题, 我也是刚进公司不久, 估计生产环境出现过端口冲突启动失败, 我按我上述代码实现先把
> 
> dubbo支持多协议，多端口的，上述代码会有问题的

目前自测是可以的,   按上述配置文件只使用到单协议单端口把, 最差的情况也只是多线程动态线程池有问题吧
