### ISSUE TITLE
ThreadPoolTaskExecutor 配合@Aync使用

### ISSUE THREAD

**Issue by lzysuqianqiu** [dromara/dynamic-tp#458]
@DynamicTp("threadPoolTaskExecutor")
    @Bean
    public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
        return new ThreadPoolTaskExecutor();
    }

   /**
     * 自定义 @Async 注解使用系统线程池
     */
    @Override
    public Executor getAsyncExecutor() {
        //return jucThreadPoolExecutor();
        //return scheduledDtpExecutor();
        return threadPoolTaskExecutor();
    }

调用报错
 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: @Bean method ThreadPoolConfiguration.threadPoolTaskExecutor called as bean reference for type [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] but overridden by non-compatible bean instance of type [org.dromara.dynamictp.core.executor.DtpExecutor]. Overriding bean of same name declared in: null] with root cause

java.lang.IllegalStateException: @Bean method ThreadPoolConfiguration.threadPoolTaskExecutor called as bean reference for type [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] but overridden by non-compatible bean instance of type [org.dromara.dynamictp.core.executor.DtpExecutor]. Overriding bean of same name declared in: null
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:386) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334) ~[spring-context-5.3.31.jar:5.3.31]
	at com.zy.config.ThreadPoolConfiguration$$EnhancerBySpringCGLIB$$8bee6e09.threadPoolTaskExecutor(<generated>) ~[classes/:na]

**Comment by KamToHung** [comment]
需要更完整的信息，我试了下@Async没问题

**Comment by yanhom1314** [comment]
是不是配置文件中定义了个叫threadPoolTaskExecutor的线程池，配置文件中定义的线程池类型是DtpExecutor，不能转为ThreadPoolTaskExecutor类型，使用姿势有问题

**Comment by lzysuqianqiu** [comment]
![image](https://github.com/user-attachments/assets/69bf46da-3c8d-4e24-a79c-8ad1890b3f58)
有ThreadPoolTaskExecutor类型的executorType？

**Comment by yanhom1314** [comment]
> ![image](https://private-user-images.githubusercontent.com/6407674/357257339-69bf46da-3c8d-4e24-a79c-8ad1890b3f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDE3MTAsIm5iZiI6MTcyMzU0MTQxMCwicGF0aCI6Ii82NDA3Njc0LzM1NzI1NzMzOS02OWJmNDZkYS0zYzhkLTRlMjQtYTc5Yy04YWQxODkwYjNmNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDkzMDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUzMjAyOGZhMDQyODc2YjEzYTYzMTI2NjQ5YWNlODRmYzg3ODNjMmI4ODI5ZTM5N2YzODYyNGU5OWFiNzIzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Myho4QyiO0qlc7m4RZMFKMpK3Qqc0WSZHfZokf3ec8Y) 有ThreadPoolTaskExecutor类型的executorType？

没有，你代码里用DtpExecutor接就行了
