### ISSUE TITLE
运行example-nacos-cloud不在日志文件输出线程池相关

### ISSUE THREAD

**Issue by sunshineboyzxy** [dromara/dynamic-tp#46]
1如下是项目bootstrap.yml截图<img width="482" alt="image" src="https://user-images.githubusercontent.com/5810974/178960083-543600ae-a54e-43da-b123-e34e38edd387.png">

2如下是dynamic-tp在nacos上相关配置的截图
<img width="662" alt="image" src="https://user-images.githubusercontent.com/5810974/178960408-df82b8d4-5d13-4f13-aaa5-61575d1fe9ce.png">
3:运行test方法项目运行正常 正常使用线程池 日志文件也生成了
<img width="768" alt="image" src="https://user-images.githubusercontent.com/5810974/178961609-260d3380-f5b6-4f93-851b-48c4a5f98367.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/5810974/178960796-1a6e0b36-7a35-48d0-80ee-0fde810e329c.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5810974/178960711-6eb573b6-f647-428a-bfa7-2dbe7036594f.png">

但是日志文件里却没有任何内容
期待文档说明的效果
<img width="806" alt="image" src="https://user-images.githubusercontent.com/5810974/178960988-e473f157-6214-4129-9444-911d7b2f3b57.png">

**Comment by lyh200** [comment]
可能我写的有点歧义，collectorType就 logging 跟 micrometer两种，没有jsonlog

**Comment by sunshineboyzxy** [comment]
已正常输出感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/dynamic-tp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/dynamic-tp] 运行example-nacos-cloud不在日志文件输出线程池相关 (Issue #46)





 
可能我写的有点歧义，collectorType就 logging 跟 micrometer两种，没有jsonlog
