### ISSUE TITLE
有几处单词拼错， 例如 ：ThreadPoolProperties 中有个单词拼错  希望修正

### ISSUE THREAD

**Issue by Jon8957** [dromara/dynamic-tp#65]
@Data
public class ThreadPoolProperties {

    /**
     * Name of Dynamic ThreadPool.
     */
    private String threadPoolName = "DynamicTp";

    /**
     * Simple Alias Name of Dynamic ThreadPool. Use for notify.
     */
    private String theadPoolAliasName;  // 这个 threadPoolAliasName  可全局搜索一下 thead
}

**Comment by yanhom1314** [comment]
可以提个pr修复下
