### ISSUE TITLE
apollo环境下使用指定的namespace,配置不生效

### ISSUE THREAD

**Issue by kazetyan** [dromara/dynamic-tp#80]
- SpringBoot 版本:2.1.5.RELEASE
- DynamicTp 版本:1.0.8
- 配置中心类型:apollo
- 问题描述:指定namespace不生效,如果把dtp-test.yml的内容移动到application里则不会打印banner并且可以打印出定义的dtp
- 使用截图（配置中心配置文件、项目配置文件、代码使用、报错信息等）
配置中心配置文件截图:
![image](https://user-images.githubusercontent.com/50894526/194791655-fb5d7620-95a5-41c3-a60c-6659df8db6b6.png)
日志截图:
![image](https://user-images.githubusercontent.com/50894526/194791745-45b1d520-8b27-4f7d-a9d3-b276f650553a.png)
![image](https://user-images.githubusercontent.com/50894526/194792293-f132917c-d46b-41f8-89c8-0ade0ce2e8bb.png)

**Comment by yanhom1314** [comment]
![图片](https://user-images.githubusercontent.com/13051908/194796009-0de734e4-8df4-423d-97a4-3a640a076870.png)
去掉.yml，配置文件名称得完全一致

**Comment by kazetyan** [comment]
> ![图片](https://user-images.githubusercontent.com/13051908/194796009-0de734e4-8df4-423d-97a4-3a640a076870.png) 去掉.yml，配置文件名称得完全一致

不行哦,properties可以不带后缀,其他的必须带后缀
![image](https://user-images.githubusercontent.com/50894526/194796844-75b62a3a-ae08-43db-bfc8-51edf2bc4ad1.png)

**Comment by yanhom1314** [comment]
![图片](https://user-images.githubusercontent.com/13051908/194812970-125d4aaa-5238-4dc8-8963-6e34e0856648.png)
参考下example，在这儿有配置吗

**Comment by kazetyan** [comment]
`apollo.bootstrap.namespaces` 没有显示配置,默认配置是`application` 会去加载`application.properties` 

我是想把当前使用的ns和dtp的区分开,期望情况是应用启动的时候去加载apollo的`application.properties` ,再根据`spring.dynamic.tp.apollo.namespace=dtp-test.yml` 去加载`dtp-test.yml` 的配置

现在实际的情况是只会加载`application.properties`

**Comment by yanhom1314** [comment]
需要配置的，apollo里创建的配置文件都要在这里配置的。项目启动会根据这些配置拉去配置的，spring.dynamic.tp.apollo.namespace=dtp-test.yml是用来配置动态刷新的

**Comment by kazetyan** [comment]
![image](https://user-images.githubusercontent.com/50894526/194835172-cdd2724b-b024-465c-b965-df74b9fdc6e8.png)

感谢,已解决,成功收到变更通知
1. 在应用内的`apollo.bootstrap.namespaces` 把`dtp-test.yml`加上
![image](https://user-images.githubusercontent.com/50894526/194832442-c11b65c3-819b-42dc-a978-4196ca682119.png)
2. apollo的`application.properties` 只保留引入dtp之前的配置,删掉dtp相关的配置,把dtp所有的配置都放在`dtp-test.yml`
![image](https://user-images.githubusercontent.com/50894526/194833367-0a5f29ee-2881-4580-9564-229976631bd8.png)

**Comment by yanhom1314** [comment]
ok
