### ISSUE TITLE
关于配置项相关优化点

### ISSUE THREAD

**Issue by NoahArno** [dromara/dynamic-tp#82]
- 目前只针对于配置的Dtp的改变进行了通知，并未对其他的参数，比如collectorTypes的改变进行相应的通知

**Comment by yanhom1314** [comment]
是的，只对核心参数变更做通知，参数太多，其他不支持

**Comment by lanqiuhuoban** [comment]
这边配置只有线程池相关的配置是动态的吗？我修改采集日志路径和采集时间，不会动态生效
logPath: /data/logs/dtp
monitorInterval: 10

**Comment by KamToHung** [comment]
> 这边配置只有线程池相关的配置是动态的吗？我修改采集日志路径和采集时间，不会动态生效 logPath: /data/logs/dtp monitorInterval: 10


是的，日志路径和采集时间是服务启动的时候确定了，不能修改
