### ISSUE TITLE
监控不到线程池参数

### ISSUE THREAD

**Issue by hardcandy** [dromara/dynamic-tp#83]
打开/actuator/dynamic-tp的信息如下：
[{"maxMemory":"7.11 GB","totalMemory":"1.61 GB","freeMemory":"1.27 GB","usableMemory":"6.77 GB"}]

接入方式：
example-nacos-cloud方式

pom文件增加：
<dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.dynamictp</groupId>
            <artifactId>dynamic-tp-spring-boot-starter-adapter-hystrix</artifactId>
            <version>${dtp.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.dynamictp</groupId>
            <artifactId>dynamic-tp-spring-cloud-starter-nacos</artifactId>
            <version>${dtp.version}</version>
        </dependency>

使用处：
@EnableAsync
@Configuration
@Slf4j
public class AsyncConfig implements AsyncConfigurer {

    @Resource
    private ThreadPoolExecutor dtpAsyncExecutor;

    @Override
    public Executor getAsyncExecutor() {
       return dtpAsyncExecutor;
    }

    @Override
    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        return (Throwable ex, Method method, Object... params) -> {
            log.error("Unexpected exception occurred invoking async method: " + method, ex);
            Cat.logEvent("asyncException", Arrays.toString(params));
        };
    }

}

nacos配置文件：
spring:
  dynamic:
      tp:
        enabled: true
        enabledBanner: true
        enabledCollect: true
        collectorTypes: micrometer,logging
        logPath: /Users/apple/logs
        monitorInterval: 5
        tomcatTp:                                    # tomcat webserver线程池配置
          corePoolSize: 100
          maximumPoolSize: 200
          keepAliveTime: 60
        jettyTp:                                     # jetty weberver线程池配置
          corePoolSize: 100
          maximumPoolSize: 200
        undertowTp:                                  # undertow webserver线程池配置
          corePoolSize: 100
          maximumPoolSize: 200
          keepAliveTime: 60
        hystrixTp:                                   # hystrix 线程池配置
          - threadPoolName: hystrix1
            corePoolSize: 100
            maximumPoolSize: 200
            keepAliveTime: 60
        executors:                                   # 动态线程池配置，都有默认值，采用默认值的可以不配置该项，减少配置量
          - threadPoolName: dtpAsyncExecutor
            threadPoolAliasName: 异步线程池
            executorType: common
            corePoolSize: 8
            maximumPoolSize: 8
            queueCapacity: 200
            queueType: VariableLinkedBlockingQueue
            rejectedHandlerType: CallerRunsPolicy
            keepAliveTime: 50
            allowCoreThreadTimeOut: false
            threadNamePrefix: Lbs-Executor-
            waitForTasksToCompleteOnShutdown: false
            awaitTerminationSeconds: 5
            preStartAllCoreThreads: false
            runTimeout: 200
            queueTimeout: 100
            taskWrapperNames: ["ttl"]
            notifyItems:
              - type: capacity
                enabled: true
                threshold: 80
                platforms: []
                interval: 120
              - type: change
                enabled: true
              - type: liveness
                enabled: true
                threshold: 80
              - type: reject
                enabled: true
                threshold: 1
              - type: run_timeout
                enabled: true
                threshold: 1
              - type: queue_timeout
                enabled: true
                threshold: 1

**Comment by dragon-zhang** [comment]
没有配置platforms，比如配置wechat，另外还要配置urlKey和receivers(以wechat为例)等必要信息。

**Comment by amosnothing** [comment]
遇到同样的问题，在 nacos 修改配置后，线程配置没有修改
