### ISSUE TITLE
关于dynamic-tp的ConfigurationPropertiesBean动态刷新原理的疑惑

### ISSUE THREAD

**Issue by road2master** [dromara/dynamic-tp#94]
SpringBoot 版本：2.5.8
DynamicTp 版本：1.0.8
配置中心类型：consul
问题描述：
请问，在consul配置中心更新配置后，客户端加了注解@ConfigurationProperties的Bean（DtpProperties）是怎么自动刷新的，在类DtpProperties处打了断点，看了源码是好像是和consul的定时任务、应用启动、类ConfigurationPropertiesBinder有关。
![image](https://user-images.githubusercontent.com/53806703/205201730-56be4a0e-475e-44b7-867a-16af976114fb.png)

**Comment by yanhom1314** [comment]
推荐看这篇文章后面的部分，看完就懂了，https://juejin.cn/post/7164283773318594597
